---
version: "3.9"
services:
  notification-service:
    build: .
    container_name: notification-service
    restart: always
    env_file:
      - .env
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
